In [1]:
import pandas as pd
import csv

In [3]:
log = pd.read_csv("./data_files/logs.csv")

/var/folders/nb/20h7pxd97n9dly3_d0vghc280000gn/T/ipykernel_76901/1097717214.py:1: DtypeWarning: Columns (34,38,39,40,47,50,53,54,57,58,59,60,62,68,70,72,73,74,76,77,78,81,85,88,89,90,91,92,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,118,120,121,122,123,129,131) have mixed types. Specify dtype option on import or set low_memory=False.
  log = pd.read_csv("./data files/logs.csv")

In [4]:
log

,row_id,player_id,school,wave,session,date,event_id,event_description,event_category,event_time,...,piece2_id,piece3_id,opponent_point_loss,player_points,opponent_points,old_rating,new_rating,priority_type_that_went_to_zero,epilogue_item_id,item_locked_unlocked_state
0,1,6427001,3561,"3561 (T,TH) Spring 2013",Session 1,2013-03-07,600,Player selects age,Avatar Creation,3M 18S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,6427001,3561,"3561 (T,TH) Spring 2013",Session 1,2013-03-07,601,Player selects gender,Avatar Creation,3M 19S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,6427001,3561,"3561 (T,TH) Spring 2013",Session 1,2013-03-07,602,Player commits to age and gender,Avatar Creation,3M 25S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,6427001,3561,"3561 (T,TH) Spring 2013",Session 1,2013-03-07,603,Player selects avatar,Avatar Creation,3M 30S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,6427001,3561,"3561 (T,TH) Spring 2013",Session 1,2013-03-07,604,Player commits to avatar and name,Avatar Creation,4M 12S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106592,2106593,65670032,1531,Single wave,Session 10,2013-12-13,706,Player pans epilogue,Epilogue,1H 36M 1S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2106593,2106594,65670032,1531,Single wave,Session 10,2013-12-13,705,Player closes Epilogue Item,Epilogue,1H 36M 5S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,True
2106594,2106595,65670032,1531,Single wave,Session 10,2013-12-13,1,Player ends session,General,1H 36M 7S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2106595,2106596,65670032,1531,Single wave,Session 10,2013-12-13,706,Player pans epilogue,Epilogue,1H 36M 7S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2106596,2106597,65670032,1531,Single wave,Session 10,2013-12-13,708,Player hits done button,Epilogue,1H 36M 7S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
player1_log = pd.read_csv("./data_files/player-6427031 copy.csv")
player1_log

/var/folders/nb/20h7pxd97n9dly3_d0vghc280000gn/T/ipykernel_84798/775907234.py:1: DtypeWarning: Columns (38,39,40,47,88,89,90,91,92,129,131) have mixed types. Specify dtype option on import or set low_memory=False.
  player1_log = pd.read_csv("./data_files/player-6427031 copy.csv")

,row_id,player_id,school,wave,session,date,event_id,event_description,event_category,event_time,...,piece2_id,piece3_id,opponent_point_loss,player_points,opponent_points,old_rating,new_rating,priority_type_that_went_to_zero,epilogue_item_id,item_locked_unlocked_state
0,308289,6427031,3561,3561 YES! Program Fall 2013,Session 1,2013-10-23,600,Player selects age,Avatar Creation,12S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,308290,6427031,3561,3561 YES! Program Fall 2013,Session 1,2013-10-23,601,Player selects gender,Avatar Creation,14S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,308291,6427031,3561,3561 YES! Program Fall 2013,Session 1,2013-10-23,602,Player commits to age and gender,Avatar Creation,15S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,308292,6427031,3561,3561 YES! Program Fall 2013,Session 1,2013-10-23,603,Player selects avatar,Avatar Creation,18S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,308293,6427031,3561,3561 YES! Program Fall 2013,Session 1,2013-10-23,604,Player commits to avatar and name,Avatar Creation,36S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7326,315615,6427031,3561,3561 YES! Program Fall 2013,Session 8,2013-12-11,815,Player cycles through Opportunity Cards using ...,Priority Sense,54H 4M 54S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7327,315616,6427031,3561,3561 YES! Program Fall 2013,Session 8,2013-12-11,815,Player cycles through Opportunity Cards using ...,Priority Sense,54H 4M 55S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7328,315617,6427031,3561,3561 YES! Program Fall 2013,Session 8,2013-12-11,815,Player cycles through Opportunity Cards using ...,Priority Sense,54H 4M 56S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7329,315618,6427031,3561,3561 YES! Program Fall 2013,Session 8,2013-12-11,815,Player cycles through Opportunity Cards using ...,Priority Sense,54H 4M 57S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7330,315619,6427031,3561,3561 YES! Program Fall 2013,Session 8,2013-12-11,816,Player picks card,Priority Sense,54H 5M 53S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
player_1_notNull = player1_log.iloc[:, 15:]
player_1_notNull[player_1_notNull.notna() == True & player_1_notNull.columns.str.contains("_id")].select_dtypes(exclude = 'float')

,skill_id,object_id,object_locked,object_first_time_unlocked,scan_start_point,scan_end_point,object_scan_result,animatic_id,avatar_gender,avatar_name,...,clip3_validity,opponent_attack_id,chosen_opponent_attack_type_id,strategy_id,piece_id_2,piece1_id,piece2_id,piece3_id,priority_type_that_went_to_zero,item_locked_unlocked_state
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
player_1_notNull.dtypes

skill_level_know                   float64
skill_level_priority               float64
skill_level_people                 float64
skill_level_refusal                float64
skill_level_me                     float64
                                    ...
old_rating                         float64
new_rating                         float64
priority_type_that_went_to_zero     object
epilogue_item_id                   float64
item_locked_unlocked_state          object
Length: 117, dtype: object

In [5]:
pd.options.display.max_rows = 4000
p = player1_log.iloc[:, 15:].notna().sum()
p.sort_values(ascending = False)

event_type                         7331
name_of_file                       7331
minigame_level                     3857
starter_statement_id                915
npc_id                              885
scan_start_point                    712
scan_end_point                      712
priority_type                       611
opportunity_card_id                 519
object_id                           497
card_id                             487
npc_fact_data_type                  480
pan_scene_start_left                426
pan_scene_end_left                  426
object_scan_result                  336
invitation_id                       297
fact_card_id                        289
sense_id                            233
opponent_its_on_statement_id        225
inviting_npc_id                     198
inviting_npc_rank_id                198
aa_level_id                         184
object_first_time_unlocked          161
object_locked                       161
chunk_id                            157
piece_id                            157
minigame_id                         110
strategy_id                         107
validity                            107
strike                               99
points_lost_gained                   99
chosen_response                      99
choice_id                            95
cred_lost_gained                     93
influence_id                         89
previous_rank_id                     88
new_rank_id                          88
amount_lost                          84
losing_priority_type                 84
resulting_priority_type              84
priority_protected_true_false        84
gaining_priority_type                84
amount_gained                        84
starting_screen_pan_position_h       83
ending_screen_pan_position_h         83
ending_screen_pan_position_w         83
starting_screen_pan_position_x       83
ending_screen_pan_position_x         83
ending_screen_pan_position_y         83
starting_screen_pan_position_w       83
starting_screen_pan_position_y       83
piece_id_2                           71
animatic_id                          70
old_choice_id                        62
priority_type_2                      60
new_choice_id                        55
players_chosen_response_id           45
animatic_time_left                   35
animatic_time_elapsed                35
player_point_loss                    33
skill_level_know                     32
skill_level_priority                 32
skill_level_refusal                  32
skill_level_me                       32
skill_level_people                   32
answer_validity                      29
stop_think_id                        25
old_skill_point                      23
new_skill_point                      23
skill_id                             23
stars_for_this_level_old             21
opponent_attack_id                   21
chosen_opponent_attack_type_id       21
stars_for_this_level_new             21
chosen_fact_card_id                  20
opponent_point_loss                  18
strategy_strength                    18
piece1_id                            18
piece2_id                            18
piece3_id                            18
player_won                           15
epilogue_item_id                     14
intention_id                         11
clip1_validity                       10
clip3_validity                       10
influence_id3                        10
clip2_validity                       10
influence_id2                        10
influence_id1                        10
total_points                          8
total_strikes                         8
missed_safe_invitations               8
accepted_unsafe_invitations           8
player_points                         7
opponent_points                       7
real_date_time                        7
json_gamestate_dump                   7
goal2_achieved_amount                 7
goal_1_priority_type                  7
goal1_amount                          7
goal1_achieved_amount                 7
goal_2_priority_type                  7
goal2_amount                          7
proportion_complete                   7
item_locked_unlocked_states           7
item_locked_unlocked_state            6
players_cred_total                    6
new_label                             5
draws_remaining                       5
old_rating                            4
new_rating                            4
avatar_age                            2
avatar_id                             2
priority_type_that_went_to_zero       2
avatar_gender                         2
old_label                             1
avatar_name                           1
dtype: int64

In [6]:
player1_log["event_id"].unique()

array([ 600,  601,  602,  603,  604,  605,  210,  211,  213,  212,  207,
        205,  221,  220,  300,  305,  302,  303,  304,  306,  203,  100,
        102,  200,  219,  216,  217,  218,  204, 1003, 1004,  900,  901,
        904, 1002,  902,  903,  905,  906,  907,  908,  909,  910,  911,
       1005, 1001,  800,  801,  814,  815,  816,  803,  804,  805,  806,
        807,  808,  809,  810,  818,  811,  400,  401,  402,  405,  406,
        411,  403,  404,  412,  413,  414,  415,  416,  417,  418,  419,
        407,  408,  420, 1000,  409,  410,  103,  104,  105,  703,  706,
        707,    1,  708,  500,  501,  502,  503,  504,  505,  506,  507,
        508,  509,  510,  511,  512,  513,  514,  515,  516,  517,  301,
        704,  705,  101,  817,  912,  812,  813])

In [45]:
timelogs = player1_log[['event_time_dbl']]
timelogs.iloc[1]

event_time_dbl    14
Name: 1, dtype: int64

In [46]:
len(timelogs)

7331

In [55]:
play_start = int(timelogs.iloc[0])
play_end = 0
total = 0
print("Real time: " + str(int(timelogs.iloc[len(timelogs) - 1]) / 3600))

for i in range(1, len(timelogs)):
  row = int(timelogs.iloc[i])
  play_end = row

  if i == (len(timelogs) - 1): 
    total = total + (play_end - play_start)
    #print("Ending calculate: " + str(play_end - play_start))
    break 

  row1 = int(timelogs.iloc[i + 1])

  if ((row1 - play_end) / 3600) > 12:
    total = total + (play_end - play_start)
    #print("Calculate: " + str(play_end - play_start))
    play_start = row1

print("Actual playing time: " + str(total/3600) + " hours")

Real time: 54.098055555555554
Actual playing time: 6.568611111111111 hours

In [51]:
total

23647

In [ ]:
big_timelogs = log.groupby("player_id").last()
big_timelogs = timelogs[['event_time_dbl']]